# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-09 10:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fullforms', '0004_fullforms_approve'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fullforms',
            name='approve',
        ),
    ]
