# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-09 10:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fullforms', '0005_remove_fullforms_approve'),
    ]

    operations = [
        migrations.AddField(
            model_name='fullforms',
            name='approve',
            field=models.BooleanField(default=False),
        ),
    ]
